version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: 'back-bix-tecnologia'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdatabase

volumes:
  postgres:
